### ISSUE TITLE
ROM 119 has outdated Chat UI data

### ISSUE THREAD

**Issue by Verthae** [Drauku/FFXI-Vision#2]
In the retail FFXI client, there was a chat update that relies on something in the [119 Dat folder](https://github.com/Drauku/FFXI-Vision/tree/master/FFXI-map-dats/ROM/119).
This folder seems to just be related to the UI, not particularly the Maps, so this file either needs to be updated or removed before applying it to an installation, as it will cause a crash upon trying to full screen the chat window.

**Comment by Drauku** [comment]
Thank you for letting me know about this issue.

I will add a warning to the `readme.md` file about this issue, but will not be updating the repository. These notated maps are primarily used on private servers which tend to be version-locked, thereby requiring the older version of the `/ROM/119/` `.dat` files. 

TBH, I would need to spend quite a while figuring out what the change was, and how to remove it from the .dat file, and I do not have the time available for that project. If you happen to have an updated or replacement, I would be happy to create "retail" and "custom" branches, but I cannot guarantee I will be able to keep up with the project.

**Comment by vekien** [comment]
Sorry to "bump" this, Me and my friend both had this happen, 100% garaunteed always crash when maximising chat.

If this happens, you can download the files here (if you're an idiot like me who overwrites and doesn't use pivot lol)
https://github.com/KenshiDRK/XiView/tree/master/ROM/119

**Comment by oakiedoak** [comment]
Hey there. This is still happening as of today. I'm trying to find the original .DAT now instead of re-installing the whole client. This is really frustrating.

**Comment by vekien** [comment]
[roms.zip](https://github.com/Drauku/FFXI-Vision/files/9282767/roms.zip)

Here is 51 and 57 dats that will fix the issue, up to date. Then just dont overwrite with vision.

**Comment by Drauku** [comment]
I have added links in the main `readme.md` to the [KenshiDRK/XiView](https://github.com/KenshiDRK/XiView) repository, as suggested by @viion (Thanks!)
